[package]
name = "colorchoice-clap"
version = "1.0.3"
description = "Clap mixin to override console colors"
repository = "https://github.com/rust-cli/anstyle"
categories = ["command-line-interface"]
keywords = ["clap", "cli", "color", "terminal", "ansi"]
license.workspace = true
edition.workspace = true
rust-version.workspace = true
include.workspace = true

[package.metadata.release]
pre-release-replacements = [
  {file="CHANGELOG.md", search="Unreleased", replace="{{version}}", min=1},
  {file="CHANGELOG.md", search="\\.\\.\\.HEAD", replace="...{{tag_name}}", exactly=1},
  {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}", min=1},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n## [Unreleased] - ReleaseDate\n", exactly=1},
  {file="CHANGELOG.md", search="<!-- next-url -->", replace="<!-- next-url -->\n[Unreleased]: https://github.com/rust-cli/anstyle/compare/{{tag_name}}...HEAD", exactly=1},
]

[dependencies]
colorchoice = { version = "1.0.0", path = "../colorchoice", default-features = false }
clap = { version = "4.3.5", default-features = false, features = ["std", "derive", "color"] }

[dev-dependencies]
anstream = { path = "../anstream" }
clap = "4.4.10"
owo-colors = "3.5.0"
